winlogbeat.event_logs:
  - name: Application
    fields: { winlog.event_name: application }
    fields_under_root: true
    tags: ["application"]
  - name: Security
    fields: { winlog.event_name: security }
    fields_under_root: true
    tags: ["security"]
  - name: System
    fields: { winlog.event_name: system }
    fields_under_root: true
    tags: ["system"]
  - name: Autoruns
    fields: { winlog.event_name: autoruns }
    fields_under_root: true
    tags: ["autoruns"]
  - name: ActiveDirectory
    fields: { winlog.event_name: activedirectory }
    fields_under_root: true
    tags: ["activedirectory"]
  - name: Microsoft-Windows-PowerShell/Operational
    fields: { winlog.event_name: powershell }
    fields_under_root: true
    tags: ["powershell"]
  - name: Microsoft-Windows-Sysmon/Operational
    fields: { winlog.event_name: sysmon }
    fields_under_root: true
    tags: ["sysmon"]

output.logstash:
  hosts: ["logstash:5044"]

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
