---
- hosts: 127.0.0.1
  connection: local 
  gather_facts: no
  become: yes
  tasks:

  - name: install python-pip
    yum:
      name: python2-pip-8.1.2-8.el7.noarch
      state: present
      allow_downgrade: yes

  - name: downgrade pip to 8.1.2 because of wacky stuff with ssl_match_hostname
    pip:
      name: pip==8.1.2

  - name: pip install pywinrm
    pip:
      name: pywinrm
