---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: yes
  tasks:

  - name: Install nmap
    package:
      name: nmap
      state: latest

  - name: Find windows host
    script: /opt/playbooks/windows-dc/get-win-ip.sh
    register: win_ip

#  - name: replace ip
#    lineinfile:
#      dest: /opt/playbooks/windows-dc/win_hosts
#      regexp: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
#      line: "{{ win_ip.stdout }}"

  - name: Add windows dc host
    add_host:
      hostname: "{{ win_ip.stdout }}"
      ansible_port: 5985
      ansible_user: admin
      ansible_password: admin
      ansible_connection: winrm
      ansible_winrm_transport: basic
      groups:
      - win
 
- hosts: win

  tasks:
  
  - name: Flush DNS
    win_command: ipconfig /flushdns 
