---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  become: yes
  tasks:

  - name: Install nmap
    package:
      name: nmap
      state: latest

  - name: Find windows host
    script: ./get-win-ip.sh
    register: win_ip

  - name: replace ip
    lineinfile:
      dest: ./win_hosts
      regexp: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
      line: "{{ win_ip.stdout }}"
       
