- hosts: localhost
  #vars:
  #  lh_ip: "{{ ansible_default_ipv4.address }}"
  tasks:

#  - name: set localhost IP
#    set_fact:
#      lh_ip: "{{ ansible_default_ipv4.address }}"
#    delegate_to: localhost

#  - name: "Copy fact to other servers"
#    set_fact:
#      lh_ip: "{{ lh_ip }}"
#    delegate_to: "{{ item }}"
#    delegate_facts: True
#    with_items: "{{ groups['all'] }}"
#    when: item != "localhost"

  - name: Install nmap
    package:
      name: nmap
      state: latest

  - name: Find windows host
    script: /opt/playbooks/windows-dc/get-win-ip.sh
    register: win_ip

  - name: replace ip
    lineinfile:
      dest: /opt/playbooks/windows-dc/win_hosts
      regexp: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$'
      line: "{{ win_ip.stdout }}"

  - name: Set DNS to Windows DC
    net_system:
      domain-search:
        - windomain.local
      name_servers:
        - "{{ win_ip.stdout }}"

  - name: Add windows dc host
    add_host:
      hostname: "{{ win_ip.stdout }}"
      ansible_port: 5985
      ansible_user: admin
      ansible_password: admin
      ansible_connection: winrm
      ansible_winrm_transport: basic
      groups:
      - win
