---
- hosts: all
  tasks:
  - name: Install auditbeat
    win_chocolatey:
      name: auditbeat
      state: present
      version: 6.7.1
  - name: Copy auditbeat yml
    win_copy:
      src: ./beats/auditbeat/auditbeat.yml
      dest: 'c:\ProgramData\chocolatey\lib\auditbeat\tools\auditbeat.yml'
      remote_src: no
  - name: Restart auditbeat
    win_service:
      name: auditbeat
      state: restarted
