---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install nxlog
    win_chocolatey:
      name: nxlog
      state: present
  - name: Copy nxlog conf
    win_copy:
      src: ./nxlog/nxlog.conf
      dest: 'C:\Program Files (x86)\nxlog\conf\nxlog.conf'
      remote_src: no
  - name: Restart nxlog
    win_service:
      name: nxlog
      state: restarted
