---
- hosts: all
  tasks:
  - name: Install packetbeat
    win_chocolatey:
      name: packetbeat
      state: present
      ignore_dependencies: yes
      version: 6.7.1
  - name: Copy packetbeat yml
    win_copy:
      src: ./beats/packetbeat/packetbeat.yml
      dest: 'c:\ProgramData\chocolatey\lib\packetbeat\tools\packetbeat.yml'
      remote_src: no
    tags: config-update
  - name: Restart packetbeat
    win_service:
      name: packetbeat
      state: restarted
    tags: config-update
