---
- hosts: all
  tasks:
  - name: Install NotepadPlusPlus
    win_chocolatey:
      name: NotepadPlusPlus
      state: present
  - name: Install VMware Tools
    win_chocolatey:
      name: vmware-tools
      state: present
  - name: Install sysinternals
    win_chocolatey:
      name: sysinternals
      state: present
  - name: Windows reboot
    win_reboot:
