filebeat.inputs:
- type: log
  paths:
    - c:\pslogs\*\*.txt
  fields: {log_type: powershell-logs}

output.logstash:
  hosts: ["logstash:5045"]

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
