packetbeat.interfaces.device: 0

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
  - type: icmp

  - type: dns
    ports: [53]
    include_authorities: true
    include_additionals: true

  - type: dhcpv4
    ports: [67, 68]

  - type: http
    ports: [80, 8080, 8000, 5000, 8002]

packetbeat.procs.enabled: true

output.logstash:
  hosts: ["logstash:5046"]

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["http://elasticsearch:9200"]
