---
- hosts: all
  gather_facts: no
  tasks:
  - name: Install winpcap
    win_psexec:
      command: powershell.exe -ExecutionPolicy ByPass -Command choco install winpcap -y --force
      elevated: yes
      interactive: yes
  - name: Install packetbeat
    win_chocolatey:
      name: packetbeat
      state: present
      ignore_dependencies: yes
  - name: Copy packetbeat yml
    win_copy:
      src: ./beats/packetbeat/packetbeat.yml
      dest: 'c:\ProgramData\chocolatey\lib\packetbeat\tools\packetbeat.yml'
      remote_src: no
  - name: Restart packetbeat
    win_service:
      name: packetbeat
      state: restarted
